### ISSUE TITLE
How to get values of input text onEdit, onDelete and onAdd functions

### ISSUE THREAD

**Issue by manojrhr** [t-edson/bootstable#2]
Hi, First thanks for this great library. 

I just want to know that how can I get values of input text onEdit, onDelete and onAdd functions of the which I edit and update the same in database using ajax.

**Comment by t-edson** [comment]
The event OnEdit() just give the row edited. OnAdd() doesn't give information of row because it's always de last row. 
There as an issue with OnDelete, that probably can help you:  https://github.com/t-edson/bootstable/issues/1
This library only give information about the row edited, deleted or added, not about the specific column. Additional code is needed to do this. Maybe it's better you update all the row, when changed. 
Or if the table is small, I prefer to send all the entire table and not worried about rows or columns.

**Comment by t-edson** [comment]
Check the last version. It has implemented the event onBeforeDelete().
